### PR TITLE
Game Boy Color, Game Boy Pocket Light / Dark Mode, Invert colors

### PR DESCRIPTION
**Pull request by mattakins**
### Game Boy Color (handheld)
Created a version of the handheld/gameboy shader that supports Game Boy Color games.

### Game Boy Pocket Light / Dark Mode (handheld)
Light and dark mode versions of the handheld/gameboy-pocket shader.

### Invert colors (misc)
Added a shader that inverts colors.

### CODE REVIEW

**Comment by nfp0** [comment]
If these are to be merged I think they would benefit of more specific naming.
"gameboy-color" and "gameboy-pocket" convey that these are standard shaders trying to replicate the console's screen, which is not the case. These have effects far different from the real consoles.

**Comment by mattakins** [comment]
They follow the naming format of the shader in the ‘handheld’ folder that they are based on - ‘gameboy-pocket.slang’.

**Comment by hizzlekizzle** [comment]
Do you have any full-res screenshots of these that I could take a look at without having to clone and load everything?

Beyond that, I have a couple of questions/notes:
1. Did you run those pngs through an optimizer/crusher yet?
2. How much did those shader passes change the original. They look pretty similar just at a glance, so would it be possible to integrate some or all of them back into the original and just switch among them with a parameter to reduce code-duplication?
3. I see you have 2 copies of the color inversion shader, one in misc and one in handheld. Was this intentional? If so, what'd you have in mind?
4. Instead of a new, single-purpose shader to invert colors, would it make sense to add that functionality to the image-adjustment shader?

**Comment by mattakins** [comment]
Thanks for the feedback! Here is some follow up with screenshots below:

1. No - I am referencing pngs that exist already in the handheld/shaders/gameboy/resources folder. However, I redid the gameboy-color shader to reference these original images.
2. Good idea. I will try to code light / dark / original mode into the 'gameboy-pocket' shader as a parameter. I think 'gameboy-color' still makes sense as a standalone. Open to more suggestions here. I also am working on the 'gameboy-color' shader modifying the original 'gameboy' shader files to avoid code duplication.
3. The color inversion shader is used to create the gameboy-pocket-dark. I realize this would make sense coded into the shader as opposed to referencing a separate shader.
4. I agree with invert colors being a parameter in image-adjustment as opposed to a standalone.

### gameboy-color
Pokemon Crystal-240205-133021
The Legend of Zelda - Oracle of Seasons-240205-132939
This makes more visual sense on handheld devices.

### gameboy-pocket-light
50 Shadow Warriors-240205-133228

### gameboy-pocket-dark
50 Shadow Warriors-240205-133252

Compare to the original 'gameboy-pocket' shader
50 Shadow Warriors-240205-133615

**Pull request closed without merging**
