### PR TITLE
CRT Maximus Royale filter added

### PR DESCRIPTION
**Pull request by DigiDwrf**
Based on CRT Royale, this filter includes a lot of cool features:

- Horizontal ringing (produced by low pass filters e.g. SNES video output)
- CVBS / S-VIDEO / RGB filter modes
- Accurate pixel perfect dimensions (for 1080 resolutions and up)
- TV frames that reminds the 90's experience
- PC monitor frame also available
- New adjustable scale system to fix image size and overscans
- Ambient lighting and rear LED simulation modes
- Reflections over the screen borders
- Nice bulged screen finish
- Auto scales to any resolution, preserving 4:3 ratio
- 3 shaders available: normal mode, fast mode and doubled resolutions output mode

Glcore and d3d11 drivers supported at the moment.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This looks good! The only requests I have are:
1. can you make sure the presets are full-fat (i.e., with complete paths rather than include statements), since not every program that uses our shaders supports that sort of thing?
2. are the bezel images as compressed as possible?

**Comment by DigiDwrf** [comment]
@hizzlekizzle thanks!

1. Sure, I can make those changes. I noticed that other shaders uses that full-fat formating too, I did the way I did because it was easy to handle and uses less code, but I can change it 👍 

2. Yes, otherwise it would look not that good, all images together (bezels and phosphor shapes) uses just 6.11 mb, please let me know if there's a limit for that, or if it's ok.

**Comment by hizzlekizzle** [comment]
Yeah, I think the filesize is fine. I try to make sure everyone compresses them as much as possible to keep it to a minimum (we've had people submit unnecessarily huge pics in the past), but after a point, it's just the price of progress :)

**Comment by DigiDwrf** [comment]
I'm updating the code ASAP :)

**Comment by DigiDwrf** [comment]
OK, done! @hizzlekizzle let me know if it looks good now.

**Comment by stholt5233** [comment]
sorry for commenting to an old post, but need some help with this shader...Not sure what happened, was working perfectly for a while but now if I apply it, the game screen is only about 1/4 the display size and right in the middle, the bezel is full size??

**Comment by hizzlekizzle** [comment]
Hmm, when did this start? There have only been 2 changes to this shader since it was initially committed: one to change the "Original" references to a stock pre-pass to make it play nicer with the append/prepend preset option and then another one to initialize a variable to 0.0 instead of leaving it undefined in some cases, which was causing intel IGPs to go crazy.

**Comment by stholt5233** [comment]
Okay, so I figured out some of the issue...On my laptop, the shader works
great on most cores, NES, SNES, Genesis, etc...however the side borders of
the Megabezel get cut off when using it for a PS1 core.  The small screen
issue was only on my XBox series S install, but I found the shader
parameter to fix that...the sides of the Megabezel are still missing on all
cores though.  Sorry for the confusion and my poor recall at the time.  I
tried to find shaper parameters that controlled the display of the
Meghabezel shader, but could not figure it out.

**Comment by HyperspaceMadness** [comment]
I'm not sure how this relates to the Mega Bezel, but if the sides of the image are cut off then it's probably because you are not using the FULL scaling mode in video settings. You can check the Mega Bezel readme for full setup instructions.

**Comment by DigiDwrf** [comment]
hey @stholt5233, this shader is not related with the Mega Bezel shader, I used the CRT Royale filter as the base filter, tweaked some parameters, and added my own code to improve phosphor simulation and add cool stuff. Can you share any print screen showing the issue you're having? Maybe I can help you

**Pull request merged**
