### PR TITLE
ngpc-3x: fix border (AlvaroBurnett)

### PR DESCRIPTION
**Pull request by BlinkBlank**
https://github.com/libretro/RetroArch/issues/11741

### CODE REVIEW

**Comment by Tatsuya79** [comment]
It's using a border shader that is resolution dependant.
It's been made for 1440p and you're going to change its default for 1080p.

**Comment by BlinkBlank** [comment]
Hmm. That's bad.

Original author @AlvaroBurnett should be notified.

**Comment by AlvaroBurnett** [comment]
Hmm ok so this shader should be modified to make it resolution independent. Is that right?

**Comment by Tatsuya79** [comment]
It could use gb-pass-5 instead of border.slang like the other console-border presets.
That's what I'm doing in my pack:
https://forums.libretro.com/t/handheld-border-shaders/2551

**Pull request closed without merging**
