### PR TITLE
New NTSC shader by PlainOldPants

### PR DESCRIPTION
**Pull request by PlainOldPants**
This is another one of those sudden big poll requests from out of nowhere that you don't have the time to review. (Not really so sudden if you saw what I posted on the Libretro forums about 10 days ago.)

This work-in-progress NTSC shader has the following features that overheat your GPU:

* Built-in test patterns: 100% color bars, stepped color ramps (15 steps), HSV spectrum, HSV spectrum with key areas widened, and full NES palette. The test patterns will go through the entire NTSC signal process (including bright red bleeding), so be careful with this.
* Detecting and compensating for the user's cropped overscan, assuming the same amount was cropped from both sides
* Correction for Genesis Plus GX's colors, not needed for BlastEm. Still haven't tested PicoDrive.
* NES video signal support via Mesen's "raw" palette. (Last time I checked, something was wrong with FCEUmm's raw palette.)
* Configurable color carrier that should be able to match a lot of consoles, instead of being stuck with these mysterious video game consoles called "2 phase" and "3 phase" that I really want to buy but can't find anywhere.
* Inside the console, configurable lowpass on luma and bandpass on chroma before combining the signals together. The default for both is a basic sinc window FIR filter from artifact-colors, but there are other options, including an unfinished port of the 3-band equalizer from NTSC-CRT by EMMIR.
* Genesis/MegaDrive chroma jailbars. Not sure how this works on real hardware, but adding a sine wave onto the signal emulated it well.
* Inside the CRT, configurable lowpass and bandpass filters to isolate the luma and chroma signals. The options are the same as for the console, so be careful not to get the two confused.
* R-Y and B-Y demodulation based on data from real jungle chips' data sheets (or plain Rec. 601 / Rec. 709 if you prefer). This means you can get Sony CXA2025AS color on consoles other than NES now. I highly doubt any mainstream hardware ever bothered with the different band limits on I and Q, so I left that out on purpose.
* Knobs for contrast, brightness, color, and tint. (Unfortunately, there is no sharpness setting. The Sony CXA2025AS's data sheet has a graph about it, but I don't know what to do.)
* Optional color bleeding (mostly bright red) whenever a color is too high. Not sure how this works on real hardware, so I took an educated guess. This color bleeding feature looks nasty and causes a serious drop in performance, so it might be better to turn it off.
* Optional gamma correction using either BT.1886 or a basic power function.

The Genesis/MegaDrive presets are just matched by eye. I just added the bandpass on chroma before decoding just today, so the luma fringing artifacts are quite far off. I seriously need to focus on my university coursework, so I think this is a good stopping point on this project.

I hope that people will be able to use this shader to try to match real consoles and CRTs more closely than they could before, though there's obviously still a long way to go before calling this "accurate", particularly due to the FIR filter causing ringing both to the left and to the right. I still don't know what "2 phase" and "3 phase" really are.

Notice how the conversion from linear space to sRGB space is in a separate shader pass. This is to allow you to add an additional pass for a chromaticity conversion in linear space, preferrably using a precomputed lookup table. I had ones for P22-80s and P22-90s set up using ChthonVII's program called gamutthingy, but I found out today that it's not working, as there's some glitch causing a visible staircase effect in the resulting lookup tables, especially in blue. For now, I am omitting the gamut lookup table.

Doraemon - Yume Dorobou to 7 Nin no Gozans (Japan)-240826-175114
Battletoads (USA)-240826-181159

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
This looks good. Thanks for the contribution!

My one minor request is that the mesen RAW palette shader be moved to the nes_raw_palette directory.

**Comment by PlainOldPants** [comment]
I see. I'll move that to the nes_raw_palette directory, then. I'm also going to add some gamut LUTs really quick.

**Comment by hizzlekizzle** [comment]
k, have those pngs been optimized? I'm assuming yes, based on their size but just want to check

**Comment by PlainOldPants** [comment]
I'm new-ish to this, so I don't know if they've been optimized. They are exported from this program called [gamutthingy](https://github.com/ChthonVII/gamutthingy) which internally uses <png.h> from libpng-dev, and I haven't done any further changes to the PNGs that were exported.

**Comment by hizzlekizzle** [comment]
There are a bunch of png "optimizers" online, like this one: https://compresspng.com/

I think they pretty much all use the same software under the hood. If they only net a couple of KBs, it's probably not worth committing, but they often save 50-70%, which is usually worthwhile. Just make sure you try using one after the compression because they're not always as "lossless" as they claim.

**Comment by PlainOldPants** [comment]
I tried several different sites (including the one you linked), and all of them keep giving me this same garbage result for P22-80s.

Doraemon - Yume Dorobou to 7 Nin no Gozans (Japan)-240827-180528

The one you linked did work for 90s, J, and Trinitron, with about 30% space compressed, so I have committed these. I have also done a minor fix on all the gamuts, namely re-enabling the "spiral carisma" feature.

**Comment by hizzlekizzle** [comment]
Ah, great savings on those that were crush-able, and no worries on the one(s) that wouldn't. I'm glad you checked them and found the issue before we committed them :)

So you think it's all ready to go, then? No more last-minute additions?

**Comment by PlainOldPants** [comment]
That's all. Now it's done.

**Comment by hizzlekizzle** [comment]
hey, @PlainOldPants, some of the shaders and presets inside the patchy-ntsc directory seem to be WIP/broken. Do you have any objection to me nuking those?

**Comment by PlainOldPants** [comment]
No problem. Those old, outdated slangp files were left in there on accident.

On another note, I've still been making minor updates to this on the LibRetro forums, since I didn't want to keep spamming those on here. Since you're here right now, this might not be a bad time to update to the latest version.

**Pull request merged**
