### PR TITLE
add blue noise dithering

### PR DESCRIPTION
**Pull request by gizmo98**
Add two shaders and three presets.
- blue noise: static blue noise dithering pattern
- blue noise dynamic: blue noise dithering pattern which changes from frame to frame
- blue noise monochrome: a variant for monochrome output

https://forums.libretro.com/t/blue-noise-dithering-shader/41636

### CODE REVIEW

**Comment by gizmo98** [comment]
~2,7MB textures. I can try to use some smaller 64x64 or 32x32 textures if size is a problem. I just need to check if end result looks ok.

**Comment by hizzlekizzle** [comment]
I don't have any hard-and-fast rule, no, just trying to keep things as light as possible, since they are bundled with almost every RetroArch build.

**Comment by gizmo98** [comment]
Ok. I try to squeeze it and report back.

**Comment by hizzlekizzle** [comment]
Much better! Thanks for working on it. Are you ready for merge?

**Comment by gizmo98** [comment]
@hizzlekizzle stripped it down to just one 220kb texture. Should be small enough now.

**Comment by gizmo98** [comment]
> Much better! Thanks for working on it. Are you ready for merge?

Yes. Can be merged.

**Pull request merged**
