### PR TITLE
Handheld border single scaling parameter, allowing for arbitrary scaling levels (4K compatibility)

### PR DESCRIPTION
**Pull request by nfp0**
This simplifies the way scaling is done in the handheld border shaders by removing the need to use `OUT_X` and `OUT_Y` parameters. The only parameter needed is the `video_scale` parameter.

It brings the following benefits:

- It allows the use of arbitrary scaling levels. Useful for 4K resolutions and higher, as the current presets were too small.
- It allows to have a single preset file for the gb-pass shaders and use the `video_scale` parameter to choose the scale value, instead of a separate preset for each scaling level.
- Less parameters to maintain in the presets files.

It works for all presets except the GBA color-motionblur and the PSP ones, hence why I mark this as draft.
I'll need to either fix those, or leave a version of the old gb-pass-5.slang just for those two.

I tested this on a Radeon RX 6800 on Linux, but I plan on testing these changes on an Nvidia on Windows and on an integrated Intel GPU before I mark it as ready.

If this ends up being merged, it might also be worth considering removing all the duplicated gb-pass presets (dmg, gb-pocket, etc) that don't need to exist anymore thanks these changes.

EDIT: All shaders have now been cleaned up. The user is now expected to change the scale of gb-pass shaders by a single shader paramenter. The scale of all the other border shaders can be changed by changing the scale value of the lcd-grid shader pass in the Shaders menu and hitting "Apply changes". The border will be automatically adjusted for both cases.

### CODE REVIEW

**Comment by nfp0** [comment]
Major cleanup done.

Remaining problems:
1) I need someone to confirm to me that the PSP shader is correctly aligned, because I have no PSP cores nor roms.
2) I don't know what to do with the NeoGeo shaders because they use border.slang with parameters specific to each zoom level.
3) The RETRO shaders also use parameters specific to each zoom level.

I don't know if the Retro shaders are very popular, but they look horrible to me. Maybe we could shove them on a "retro" or "alternatives" subfolder?

**Comment by nfp0** [comment]
4. RetroArch only allows to increase the scaling value of shaders passes up to 5x on the GUI. I don't know if this is a hard limitation, but it will prevent users from increasing the shader scale to usable values for 4K resolutions unless they edit the preset files.

**Comment by Tatsuya79** [comment]
Neogeo pocket shader can use gb-pass5 just fine.
It was left with that other border shader by mistake I think.

**Comment by nfp0** [comment]
> Neogeo pocket shader can use gb-pass5 just fine. It was left with that other border shader by mistake I think.

Alright! Cleaned it up.
Also removed the retro shaders.

**Comment by nfp0** [comment]
https://github.com/libretro/RetroArch/pull/13921 has now been merged, so I'll just wait for a new RetroArch release to mark this as ready, Just in case a user updates the slang shaders before having the ability to increase the scale in the GUI.

**Comment by Tatsuya79** [comment]
Rise from the grave.

**Comment by nfp0** [comment]
@Tatsuya79 Ready to go!
You think I should add a fake parameter explaining that to increase the shader size it should be done on the shader passes?

**Pull request merged**
