### PR TITLE
Update simple_color_controls.slang

### PR DESCRIPTION
**Pull request by metallic77**

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
I see you have 2 copies of the same bezel image. Can you just reuse the same image instead of having 2 copies of it?

Also, I see you have a GLES ifdef, but I don't think those macros survive through the SPIR-V reflection. I haven't been able to detect d3d compilers with macros, at least.

**Comment by metallic77** [comment]
These are different bezels, the first is the one used in GLSL version, the other two are Commodore 1084-S look, but if you want i can change the code to keep only one (the first anyway). You are right about GLES i just ported directly the GLSL version. But it compiles on my PC anyway lol.

**Comment by hizzlekizzle** [comment]
If they're actually different, I'm fine with merging both, I just couldn't see any difference between them:
https://raw.githubusercontent.com/libretro/slang-shaders/00a1e5830959336c9f831d44edebc1383fcb5a33/crt/shaders/bezel.png
vs
https://raw.githubusercontent.com/libretro/slang-shaders/00a1e5830959336c9f831d44edebc1383fcb5a33/crt/shaders/crt-consumer/bezel.png

**Comment by metallic77** [comment]
I think it should be ok now (?)

**Pull request merged**
