### PR TITLE
Update koko-aio to 3.5

### PR DESCRIPTION
**Pull request by kokoko3k**
Firs PR of my life, bear with me :-P

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
looks good, especially for a first PR :)

Would it be reasonable to remove the monitor body source 7z file? That is, just to keep the size down?

**Comment by kokoko3k** [comment]
Wops, yes ofc.
Is it possible to do it without redoing the PR?

**Comment by hizzlekizzle** [comment]
Sure, just delete it from the repo with git rm and make a new commit and it will update the PR with the changes.

It doesn't matter how many commits you use, as I'll just squash them all into 1 when I do the merge.

**Comment by kokoko3k** [comment]
Hi there,
is it ok now?

**Comment by hizzlekizzle** [comment]
much better, yes! thanks!

**Comment by kokoko3k** [comment]
Thank you!

**Pull request merged**
