### PR TITLE
More border shaders using gb-pass5.slang

### PR DESCRIPTION
**Pull request by pepedopolous**

### CODE REVIEW

**Comment by pepedopolous** [comment]
OK, so the first commit was already pulled in. I'm not sure how to separate the second one.... total newb here.

**Comment by hizzlekizzle** [comment]
No problem. I'll have to rebuild it anyway due to the conflicts. It doesn't really make sense to bring in the PSP image unless/until the ppsspp core starts working with vulkan, so I'll leave it out for now.

**Comment by pepedopolous** [comment]
Thanks. Actually, I think the PSP image is upside down for Cg and GLSL as well.

**Comment by pepedopolous** [comment]
Hi,

I was wondering if you can you give me a hint on how to actually fork libretro/shaders and not Themaister/slang-shaders? Then I could avoid the conflicts and keep up to date with upstream no?

**Comment by hizzlekizzle** [comment]
I think it's just a matter of hitting the 'fork' button up at the top of the page, or trying to edit a file in the web interface.

**Comment by pepedopolous** [comment]
I did hit the 'fork' button but you can't fork an already existing fork of a repo. So github gave me a fork Themaister/slang-shaders even though I wanted to fork /libretro/slang-shaders.

**Comment by hizzlekizzle** [comment]
Hmm, that's weird. I guess you could make a fork of the original repo and then clone this one and overwrite all of the other one with the new files and then push them up to your fork. There's probably some git command magic to do all of that but I don't know it :/

**Comment by pepedopolous** [comment]
So, I cloned libretro/slang-shaders, then uploaded it my repo with my handheld presets. The DSI shaders don't work (wrt coloured patches visible on the LCD screen).

**Pull request closed without merging**
