### PR TITLE
Update res-independent-scanlines.slang

### PR DESCRIPTION
**Pull request by metallic77**

### CODE REVIEW

**Comment by metallic77** [comment]
Previous version (and this) fail to load on D3D11 with "[ERROR] [slang]: Unknown semantic found". But both load ok in vulkan

**Comment by hizzlekizzle** [comment]
That's weird! How do those changes correct that??

**Comment by metallic77** [comment]
No, just saying it won't work on d3d11, had to switch to vulkan.

**Comment by hizzlekizzle** [comment]
ohhh, ok. gotcha

**Pull request merged**
