### PR TITLE
Do color correction before LCD grid and fix gamma

### PR DESCRIPTION
**Pull request by nfp0**
This is a follow-up to https://github.com/libretro/slang-shaders/pull/505

I don't tend to agree with doing color correction after the LCD shader.
I have read the justification Pokefan531 posted a few months ago, but after testing both options, it still doesn't make sense to me.

Look how different the subpixels look when using the color correction after the LCD.

Correction after LCD grid:
Pokemon - Gold Version (USA, Europe) (SGB Enhanced) (GB Compatible)-240117-225519

Correction before LCD grid:
Pokemon - Gold Version (USA, Europe) (SGB Enhanced) (GB Compatible)-240117-225605

Doing correction after the LCD grid decreases the subpixel color saturation and reduces the LCD grid effect. I don’t feel like this is the intended behavior of color and gamma correction.

Also, he suggested using the LCD grid shader gamma controls to control the gamma, but that has weird effects. For example, a full white screen should look exactly the same regardless of gamma value, as gamma does not affect full white. But look at the following test:

image

These 2 pictures should look the exact same, as gamma doesn’t affect white, but they look very different here.

This also happens if we control the gamma with the `lighten_screen` and `darken_screen` parameters. The subpixels are being affected if we do the color correction after the LCD grid, even on full white.

Additionally, I've set the GBC `lighten_screen` to a more moderate value of 0.5, as it's closer to a real GBC screen. Pokefan531 is of the same opinion on that.

### CODE REVIEW

**Comment by nfp0** [comment]
If everyone agrees on this, I can also push changes to do color correction before the LCD to the remaining lcd-grid-v2 presets, as I've only changed the GBC and GBA ones.

**Comment by hizzlekizzle** [comment]
Doing it post-LCD makes sense to me since Pokefan's GBA measurements are on the output of the physical LCD. However, the LCD shader isn't doing anything to ensure that it's affecting the image in the same way as the physical LCD.

If Pokefan's also measuring the emulator output post-LCD to ensure that the output is the same, I think that's how it needs to stay. (to be clear, I'm not sure whether this is the case or not)

**Comment by nfp0** [comment]
I understand what you mean. But I think the base `gbc-color.slang` and `gba-color.slang` are also used as stand-alone. The lcd-grid is an extra added effect.

> If Pokefan's also measuring the emulator output post-LCD to ensure that the output is the same, I think that's how it needs to stay. (to be clear, I'm not sure whether this is the case or not)

Yes, that makes sense, but I'm also not sure if that is the case or not. It would be nice to have feedback from him.
I'll try to ask him and let's wait a bit more, maybe.

**Comment by nfp0** [comment]
> Also, he suggested using the LCD grid shader gamma controls to control the gamma, but that has weird effects. For example, a full white screen should look exactly the same regardless of gamma value, as gamma does not affect full white. But look at the following test:
> 
> image
> 
> These 2 pictures should look the exact same, as gamma doesn’t affect white, but they look very different here.
> 
> This also happens if we control the gamma with the lighten_screen and darken_screen parameters. The subpixels are being affected if we do the color correction after the LCD grid, even on full white.

Please ignore what I said here. I was wrong. It seems the test I was doing was not on full-white pixels. My bad.
I have properly tested on full-white and the picture is not affected, as it should be.

Furthermore, I think I now understand the reasoning for correcting the subpixels, as Pokefan is doing, instead of correcting only the original picture.

So I will close this PR and provide a new one just with the gamma adjustment on the LCD Grid pass to properly represent the GBC and GBA screens, as Pokefan suggested me to do.

**Pull request closed without merging**
