### PR TITLE
move over 2 royale variants from glsl shaders

### PR DESCRIPTION
**Pull request by Pixelnarium**
As far as I can see it just needs a search & replace from .glsl to .slang.

### CODE REVIEW

**Comment by Pixelnarium** [comment]
Ah, I see that these shaders are already present in the upstream repo. Any reason why they are not present here?

**Comment by hizzlekizzle** [comment]
yes, they're redundant due to the ntsc-adaptive shader, which covers 256px and 320px variants at the same time.

**Comment by Pixelnarium** [comment]
Ah I see. They are in the presets directory and not in the crt directory. Sorry, I did not see that :)

**Comment by hizzlekizzle** [comment]
no worries. yeah, I moved most/all of the non-vanilla variants to the 'presets' directory because the main crt directory was getting hard to navigate

**Pull request closed without merging**
