### PR TITLE
Update crt-royale-fast and several presets

### PR DESCRIPTION
**Pull request by Hyllian**
- Presets moved to new folder presets/crt-royale/fast.
- New presets for 1080p and 4k.
- Slotmask updated.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
is there a reason you moved that one ntsc preset from the 'presets' directory to the 'crt' directory?

**Comment by Hyllian** [comment]
It isn't just a simple preset. It's a full preset. Many other simple
presets depend on it. So I thought it was necessary to put it there. If you
don't think so, I may update and bring back to presets.

Em sex., 20 de set. de 2024 15:55, hizzlekizzle ***@***.***>
escreveu:

**Comment by hizzlekizzle** [comment]
full-fat presets can go in the 'presets' directory, too. I generally try to put *most* things that incorporate several different separate shaders that and leave the building blocks in the dedicated directories. It's not a hard-and-fast rule, though.

Ideally, *only* full-fat presets should go into the repo at all, so programs that don't support the preset references could still use the shaders from the repo, but I had loosened that rule for a few shaders that relied on it extensively (i.e., Mega Bezel and Megatron). It may be worth dropping that rule altogether, though.

**Comment by Hyllian** [comment]
Ok. Tomorrow I'll work on this and make a PR update. I was even thinking about changing some names, so it'll be a good thing in the end.

**Comment by Hyllian** [comment]
PR updated now! All full-fat presets.

**Pull request merged**
