### PR TITLE
Fishcu/authentic gbc

### PR DESCRIPTION
**Pull request by fishcu**
Sample screenshots on Discord: https://discord.com/channels/184109094070779904/662208336984277012/1234234573265571913

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
Is there a reason you decided to split the parameters and 'common' parts into separate files? If so, and you don't want to merge them into the main shader, would you mind at least changing their file extension to *.inc or *.h or whatever so nobody tries to load them as a standalone slang shader passes (since they're not)?

**Comment by fishcu** [comment]
Yes, the reason I split out these files are as follows:
- The "shared" part is similar to a library of functions that this shader introduces. It has proven useful for incorporating functionality into other (combined) presets. For an example, the "blur fill" shader relies on the exported functionality of the "pixel AA" shader. I have similar plans for this LCD shader.
- The parameters are split out so that I can control the order of parameters in other combined presets, de-coupling the order of parameters from the order in which they appear in individual passes. This improves the user experience.

A survey I did back in August 2023 showed that the file endings used are pretty mixed: https://discord.com/channels/184109094070779904/584075942276628481/1136000493617958932
I don't really want to use `*.h` since that implies a C header.
I may change the file endings to `*.inc` if that helps to prevent users from opening the files. I should point out that I have been doing the inclusion of files with `*.slang` file endings, which are not stand-alone shaders, for some other presets as well, and have not gotten any reports of errors.

**Comment by hizzlekizzle** [comment]
Ah, yeah, I hadn't noticed that those weren't functional slang shaders when I merged them. You can give them whatever extension you like, but if it's going to be *.slang in a repo of slang shaders, it should be compileable as a slang shader.

**Comment by fishcu** [comment]
OK, I'll fix the files in this PR, then make another PR to fix the other files that are affected by this.

**Pull request merged**
