### PR TITLE
Create crt-guest-dr-venom-ntsc-composite-256px.slangp

### PR DESCRIPTION
**Pull request by lfanog**
crt-guest-dr-venom + ntsc-256px

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
hey, can you get these into a single PR, by chance?

**Comment by lfanog** [comment]
> 
> 
> hey, can you get these into a single PR, by chance?

Do you mean add an option in the preset to choose ntsc 256 or 320 and thus keep only the crt-guest-dr-venom-ntsc-composite file?

**Comment by hizzlekizzle** [comment]
No, I just mean: you're doing separate PRs for each action in the repo. Can you merge them into a single PR?

**Comment by lfanog** [comment]
> 
> 
> No, I just mean: you're doing separate PRs for each action in the repo. Can you merge them into a single PR?

What I have to do?

**Pull request closed without merging**
